name: Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Find solutions
        id: find-solutions
        run: |
          SOLUTIONS=$(find . -name "*.sln" | tr '\n' ' ')
          echo "solutions=${SOLUTIONS}" >> $GITHUB_OUTPUT
          echo "Found solutions: ${SOLUTIONS}"

      - name: Build
        run: |
          set -euo pipefail
          for solution in ${{ steps.find-solutions.outputs.solutions }}; do
            echo "Building $solution"
            dotnet build "$solution" --configuration Release
          done

      - name: Run tests
        run: |
          set -euo pipefail
          for solution in ${{ steps.find-solutions.outputs.solutions }}; do
            echo "Testing projects in $solution"
            dotnet test "$solution" --configuration Release --no-build --verbosity normal
          done